In [1]:
import pandas as pd      
import numpy as np 
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')

In [3]:
#pip list

In [2]:
def eval_metrics(actual, pred):
    rmse = np.sqrt(mean_squared_error(actual, pred))
    mae = mean_absolute_error(actual, pred)
    mse = mean_squared_error(actual, pred)
    score = r2_score(actual, pred)
    return print(" r2_score:", score, "\n","mae:", mae, "\n","mse:",mse, "\n","rmse:",rmse)

In [64]:
df = pd.read_csv("final_scout_not_dummy.csv")
pd.set_option('display.max_columns', None)

In [4]:
df.head(1)

make_model body_type  price             vat       km  Type    Fuel  Gears  \
0    Audi A1    Sedans  15770  VAT deductible  56013.0  Used  Diesel    7.0   

                                 Comfort_Convenience  \
0  Air conditioning,Armrest,Automatic climate con...   

                                 Entertainment_Media  \
0  Bluetooth,Hands-free equipment,On-board comput...   

                                           Extras  \
0  Alloy wheels,Catalytic Converter,Voice Control   

                                     Safety_Security  age  Previous_Owners  \
0  ABS,Central door lock,Daytime running lights,D...  3.0              2.0   

   hp_kW  Inspection_new Paint_Type Upholstery_type Gearing_Type  \
0   66.0               1   Metallic           Cloth    Automatic   

   Displacement_cc  Weight_kg Drive_chain  cons_comb  
0           1422.0     1220.0       front        3.8

In [5]:
df.shape

(15915, 23)

In [6]:
df.columns

Index(['make_model', 'body_type', 'price', 'vat', 'km', 'Type', 'Fuel',
       'Gears', 'Comfort_Convenience', 'Entertainment_Media', 'Extras',
       'Safety_Security', 'age', 'Previous_Owners', 'hp_kW', 'Inspection_new',
       'Paint_Type', 'Upholstery_type', 'Gearing_Type', 'Displacement_cc',
       'Weight_kg', 'Drive_chain', 'cons_comb'],
      dtype='object')

In [7]:
df.age.unique()

array([3., 2., 1., 0.])

In [8]:
df.hp_kW.unique()

array([ 66., 141.,  85.,  70.,  92., 112.,  60.,  71.,  67., 110.,  93.,
       147.,  86., 140.,  87.,  81.,  82., 135., 132., 100.,  96., 162.,
       150., 294., 228., 270., 137., 133.,  77., 101.,  78., 103.,  74.,
       118.,  84.,  88.,  80.,  76., 149.,  51.,  44.,  55.,  52.,  63.,
        40.,  65.,  75., 125., 120., 184., 239., 121., 143., 191.,  89.,
       195., 127., 122., 154., 155., 104., 123., 146.,  90.,  56.,  53.,
        54., 164., 163.,  57., 119., 165., 117., 115.,  98., 168., 167.])

In [9]:
df.hp_kW.min()

40.0

In [10]:
df.hp_kW.max()

294.0

In [11]:
df.km.nunique()

6691

In [12]:
df.km.max()

317000.0

In [13]:
df.km.min()

0.0

In [14]:
df.Gearing_Type.unique()

array(['Automatic', 'Manual', 'Semi-automatic'], dtype=object)

In [15]:
new_list=["age", "hp_kW", "km", "Gearing_Type", 'make_model']

In [16]:
X=df[new_list]
y=df['price']
X=pd.get_dummies(X)

In [17]:
X.sample(5)

age  hp_kW            km  Gearing_Type_Automatic  Gearing_Type_Manual  \
14913  0.0   77.0   1647.362609                       0                    1   
9372   2.0   51.0  33205.000000                       0                    1   
8859   3.0   51.0  39990.000000                       0                    1   
13633  3.0   55.0  98694.000000                       0                    1   
12509  0.0  147.0   4262.000000                       1                    0   

       Gearing_Type_Semi-automatic  make_model_Audi A1  make_model_Audi A2  \
14913                            0                   0                   0   
9372                             0                   0                   0   
8859                             0                   0                   0   
13633                            0                   0                   0   
12509                            0                   0                   0   

       make_model_Audi A3  make_model_Opel Astra  make_model_Opel Corsa  \
14913                   0                      0                      0   
9372                    0                      0                      1   
8859                    0                      0                      1   
13633                   0                      0                      0   
12509                   0                      0                      0   

       make_model_Opel Insignia  make_model_Renault Clio  \
14913                         0                        0   
9372                          0                        0   
8859                          0                        0   
13633                         0                        1   
12509                         1                        0   

       make_model_Renault Duster  make_model_Renault Espace  
14913                          1                          0  
9372                           0                          0  
8859                           0                          0  
13633                          0                          0  
12509                          0                          0

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [22]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

In [23]:
scaler.fit(X_train) 

StandardScaler()

In [24]:
X_train_scaled = scaler.transform(X_train)
X_train_scaled

array([[-1.23594841, -1.21807673, -0.86762077, ...,  2.76470333,
        -0.04609932, -0.25876085],
       [ 1.43314671, -0.28233613,  2.89519589, ..., -0.36170246,
        -0.04609932, -0.25876085],
       [-1.23594841, -0.13261764, -0.38058522, ..., -0.36170246,
        -0.04609932, -0.25876085],
       ...,
       [-1.23594841, -0.84378049, -0.86781028, ..., -0.36170246,
        -0.04609932, -0.25876085],
       [ 1.43314671,  0.42882672,  1.43056979, ..., -0.36170246,
        -0.04609932, -0.25876085],
       [ 1.43314671,  0.80312296,  0.80424586, ..., -0.36170246,
        -0.04609932, -0.25876085]])

In [25]:
X_test_scaled = scaler.transform(X_test)
X_test_scaled

array([[-1.23594841, -0.69406199, -0.82329316, ..., -0.36170246,
        -0.04609932, -0.25876085],
       [ 1.43314671, -0.84378049,  0.41943633, ..., -0.36170246,
        -0.04609932, -0.25876085],
       [ 1.43314671,  0.42882672,  0.22313312, ..., -0.36170246,
        -0.04609932, -0.25876085],
       ...,
       [-1.23594841,  1.21484882, -0.59770724, ..., -0.36170246,
        -0.04609932, -0.25876085],
       [ 0.54344834, -0.69406199, -0.33185459, ..., -0.36170246,
        -0.04609932, -0.25876085],
       [ 0.54344834,  2.18801904,  0.47507047, ..., -0.36170246,
        -0.04609932,  3.86457225]])

In [92]:
from sklearn.linear_model import Ridge
model = Ridge(alpha=.1, random_state = 0)
model.fit(X_train_scaled, y_train)

Ridge(alpha=0.1, random_state=0)

In [93]:
y_pred = model.predict(X_test_scaled)

In [94]:
eval_metrics(y_test,y_pred)

 r2_score: 0.8426860150751216 
 mae: 1983.3855961900774 
 mse: 8193007.13764847 
 rmse: 2862.342945499101


**deployment**

In [95]:
import pickle
pickle.dump(model, open('ridge_model', 'wb'))

In [96]:
my_model = pickle.load(open('ridge_model', 'rb'))

In [97]:
columns=list(X.columns)
columns

['age',
 'hp_kW',
 'km',
 'Gearing_Type_Automatic',
 'Gearing_Type_Manual',
 'Gearing_Type_Semi-automatic',
 'make_model_Audi A1',
 'make_model_Audi A2',
 'make_model_Audi A3',
 'make_model_Opel Astra',
 'make_model_Opel Corsa',
 'make_model_Opel Insignia',
 'make_model_Renault Clio',
 'make_model_Renault Duster',
 'make_model_Renault Espace']

In [98]:
my_dict = {
    "age": 2,
    "hp_kW": 105,
    "km": 100000,
    "Gearing_Type":"Automatic",
    "make_model": 'Audi A3'
}

In [99]:
df = pd.DataFrame.from_dict([my_dict])

In [100]:
df.head()

age  hp_kW      km Gearing_Type make_model
0    2    105  100000    Automatic    Audi A3

In [101]:
df = pd.get_dummies(df)
df

age  hp_kW      km  Gearing_Type_Automatic  make_model_Audi A3
0    2    105  100000                       1                   1

In [102]:
df = pd.get_dummies(df).reindex(columns=columns, fill_value=0)

In [103]:
df.head()

age  hp_kW      km  Gearing_Type_Automatic  Gearing_Type_Manual  \
0    2    105  100000                       1                    0   

   Gearing_Type_Semi-automatic  make_model_Audi A1  make_model_Audi A2  \
0                            0                   0                   0   

   make_model_Audi A3  make_model_Opel Astra  make_model_Opel Corsa  \
0                   1                      0                      0   

   make_model_Opel Insignia  make_model_Renault Clio  \
0                         0                        0   

   make_model_Renault Duster  make_model_Renault Espace  
0                          0                          0

In [104]:
prediction = my_model.predict(df)
print(prediction)

[-1.14045755e+08]


In [63]:
print("The estimated price of your car is €{}. ".format(int(prediction[0])))

The estimated price of your car is €-114057594. 
